---
required_packages:
- gcc
- amazon-linux-extras
# - yum-utils
# - device-mapper-persistent-data
# - lvm2
# - http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm

# pip_packages:
# - docker-compose

docker_packages:
- http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.107-3.el7.noarch.rpm
- containerd.io
- docker-ce
- docker-ce-cli